services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bithost\Pdfviewhelpers\:
    resource: '../Classes/*'

  Bithost\Pdfviewhelpers\EventListener\AfterCacheableContentIsGeneratedEventListener:
    tags:
      - name: event.listener
        identifier: 'bithost/pdfviewhelpers/disable-page-cache'
